stereo_calib_parameters:
  board_size: [10, 7]
  square_size: 0.024125
  image_width: 1280
  image_height: 720
  
  left_image_folder: "/home/user/code/Dev/src/calib/stereo_calib/data/left"
  right_image_folder: "/home/user/code/Dev/src/calib/stereo_calib/data/right"
  calibration_file: "/home/user/code/Dev/src/calib/stereo_calib/config/stereo_calib_result.yaml"
  output_folder: "/home/user/code/Dev/output/stereo_calib"
  
  disparity_params:
    num_disparities: 64
    block_size: 11
    pre_filter_cap: 31
    min_disparity: 0
    texture_threshold: 10
    uniqueness_ratio: 15
    speckle_window_size: 100
    speckle_range: 32
    disp12_max_diff: 1
    use_sgbm: true
