/**:
  ros__parameters:
    status_topic: "/calib_sim_isaac/status"
    raw_image_topic: "/calib_sim_isaac/raw_image"
    result_image_topic: "/calib_sim_isaac/result_image"
    window_name: "calib_sim_ui"
