default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  J1_1_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_2_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_3_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_4_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_5_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_6_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_7_joint: {has_velocity_limits: true, max_velocity: 0.2, has_acceleration_limits: false, max_acceleration: 0.0}
  J1_8_joint: {has_velocity_limits: true, max_velocity: 0.2, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_1_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_2_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_3_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_4_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_5_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_6_joint: {has_velocity_limits: true, max_velocity: 2.0, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_7_joint: {has_velocity_limits: true, max_velocity: 0.2, has_acceleration_limits: false, max_acceleration: 0.0}
  J2_8_joint: {has_velocity_limits: true, max_velocity: 0.2, has_acceleration_limits: false, max_acceleration: 0.0}
