moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - J1_1_joint
      - J1_2_joint
      - J1_3_joint
      - J1_4_joint
      - J1_5_joint
      - J1_6_joint
      - J1_7_joint
      - J1_8_joint
      - J2_1_joint
      - J2_2_joint
      - J2_3_joint
      - J2_4_joint
      - J2_5_joint
      - J2_6_joint
      - J2_7_joint
      - J2_8_joint
