# Get Marker Detection Result Service
# Request
string request_id                    # Request identifier

---
# Response
bool success                         # Operation success
string message                       # Response message
string object_class                  # Object class
float64[] position                   # Position coordinates [x, y, z] in meters
float64[] orientation                # Orientation quaternion [x, y, z, w]
float64 confidence                   # Confidence level
string frame_id                      # Frame identifier
sensor_msgs/Image image              # Image data
sensor_msgs/Image result_image       # Image data
builtin_interfaces/Time stamp        # Timestamp