<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cam_sdk_aruco_test</name>
  <version>1.0.0</version>
  <description>相机SDK Aruco测试项目 - 支持实时相机采图和本地图片文件进行Aruco码识别</description>
  <maintainer email="developer@example.com">Developer</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>OpenCV</depend>
  <depend>yaml_cpp_vendor</depend>
  <depend>cam_manage</depend>
  <depend>visualization</depend>
  <depend>log_system</depend>
  <depend>aruco_alg</depend>
  <depend>custom_msgs_comm</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>