# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - l_arm_controller
    # - l_gripper_controller
    - r_arm_controller
    # - r_gripper_controller

  l_arm_controller:
    type: FollowJointTrajectory
    joints:
      - R1-1
      - R1-2
      - R1-3
      - R1-4
      - R1-5
      - R1-6
    action_ns: follow_joint_trajectory
  # l_gripper_controller:
  #   type: GripperCommand
  #   joints:
  #     - R1-7
  #     - R1-8
  #   action_ns: gripper_cmd
  r_arm_controller:
    type: FollowJointTrajectory
    joints:
      - R2-1
      - R2-2
      - R2-3
      - R2-4
      - R2-5
      - R2-6
    action_ns: follow_joint_trajectory
  # r_gripper_controller:
  #   type: GripperCommand
  #   joints:
  #     - R2-7
  #     - R2-8
  #   action_ns: gripper_cmd