# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    l_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    l_gripper_controller:
      type: position_controllers/JointGroupPositionController


    r_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    r_gripper_controller:
      type: position_controllers/JointGroupPositionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        use_sim_time: true
        state_publish_rate: 30.0

l_arm_controller:
  ros__parameters:
    joints:
      - R1-1
      - R1-2
      - R1-3
      - R1-4
      - R1-5
      - R1-6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
l_gripper_controller:
  ros__parameters:
    joints:
      - R1-7
      - R1-8
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity
r_arm_controller:
  ros__parameters:
    joints:
      - R2-1
      - R2-2
      - R2-3
      - R2-4
      - R2-5
      - R2-6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
r_gripper_controller:
  ros__parameters:
    joints:
      - R2-7
      - R2-8
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity