# USD 转换
module: usd_converter
default_output_dir: ~/.ros_robot_workbench/usd
mesh_backend_default: openusd
urdf_backend_default: urdf_usd_converter
isaac_python: ""
python_venv: ""
merge_fixed_joints: false
fix_base: false
mesh_root_prim: mesh
expand_xacro: false
