/**:
  ros__parameters:
    calib_target_topic: "/robot_target_pose"
    calib_pose_feedback_topic: "/robot_pose"
    calib_reached_topic: "/robot_reached"
    feedback_delay_ms: 800

    nova_arm_id_topic: "/nova_arm_id"
    nova_target_pose_topic: "/nova_target_pose"
    nova_target_arm_pose_topic: "/nova_target_arm_pose"
    initial_arm_id: 0
    initial_pose: [0.30, 0.0, 0.25, 0.0, 0.0, 0.0, 1.0]
    pose_publish_hz: 10.0
    use_tf_current_pose: true
    base_frame: "base_link"
    ee_frame_arm0: "J1_6"
    ee_frame_arm1: "J2_6"
    ee_frame_arm2: "J3_6"
    ee_frame_arm3: "J4_6"
    reach_pos_tol_m: 0.005
    reach_ang_tol_rad: 0.03
    max_feedback_wait_ms: 5000
